#this is a comment
name: mywebsite
Description: My Jekyll Website

author: #specific to github
	name: Ben Kutil
	email: bkituil@mica.edu
	github: benkutil
	twitter: benkutil

permalink: pretty #category year month day /

future: true #show future posts (default)

show_drafts: false #default


